### ISSUE TITLE
Include RSVP links in email templates

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/resources#26]
Examples in https://github.com/DjangoGirls/resources/tree/master/text_templates should be updated to demonstrate usage of RSVP links - I think quite a few people use these templates as a starting point, but they don't currently include the RSVP codes at all so people are figuring it out for themselves and not always clear on how to use them.

Originally mentioned on https://github.com/DjangoGirls/djangogirls/issues/121#issuecomment-177869888. Related to https://github.com/DjangoGirls/djangogirls/issues/222

**Comment by alexanderad** [comment]
This might be addressed by #27.

**Comment by helenst** [comment]
It is indeed - thanks! :cherry_blossom::sparkles:
