### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by goanpeca** [DjangoGirls/resources#34]
Hi there, any plans for making resources for other languages?

I would be happy to help for Spanish :-).

Would it be a separate repository?  `DjangoGirls/resources-es`?

Or a separate folder within this repo?

Thanks for the awesome work :-)

---

PS: I am Django Girls Organizer (For Bucaramanga, Colombia 04/2017) and I already registered for organizing one in La Paz,Bolivia on 08/2017.

**Comment by aniav** [comment]
Hey! Sorry for not replying earlier, just going through all of our repos and cleaning up a bit. I think you can create a subdirectory for another language and we will merge it here then :)
