### ISSUE TITLE
Getting PRs reviewed/accepted? @aniav @patjouk @olasitarska 

### ISSUE THREAD

**Issue by elena** [DjangoGirls/resources#39]
Hi team!

It's been some years since any PRs were accepted in this repo. Many events are still occuring and these resources can be getting stronger and stronger!

Just wondering what the status is, happy to do some review also.

Best regards,
Elena

**Comment by amakarudze** [comment]
Hello @elena, @aniav @patjouk and @olasitarska haven't been involved with Django Girls in a while since stepping down. Feel free to do some reviews yourself. I will also take a look or you can tag @GirlGeekUpNorth for a review as well.

**Comment by elena** [comment]
Hello @amakarudze! I'd be delighted to review but don't have permissions to do so. If no one is engaged here currently I'd be happy to take responsibility and pick up the bit, I'd also be more than happy to review on the other repo https://github.com/DjangoGirls/djangogirls/ -- to confirm that's me in the bottom row here: https://djangogirls.org/en/story/
